DeveloperAcademy-POSTECH/MC3-Team11-BeyondThe3F

README.md
작업한 브랜치
- feature/ #1 
-
- resolved : #1
=> [Setting] #1 - README.md 제목 수정

README.md
작업한 브랜치
- feature/ #6 
- README.md 내용 추가
-
- resolved : #6
=> [Feat] #6 - README.md 내용 추가

Muho/README.md
작업한 브랜치
- feature/ #4 
- Muho Readme 추가
-yaho
- resolved : #4
=> [setting] #4 - Muho Readme 추가

Austin/README.md
작업한 브랜치
- feature/ #11 
-
- resolved : #11
=> [Setting] Add README.md file on Austin Dir

MC3-BeyondThe3F/MC3-BeyondThe3F/Global/Extension/ColorExtension.swift, MC3-BeyondThe3F/MC3-BeyondThe3F/Global/Extension/ViewExtension.swift, MC3-BeyondThe3F/MC3-BeyondThe3F/Global/Modifier/TypoModifier.swift, MC3-BeyondThe3F/MC3-BeyondThe3F/View/Component/TextComponentView.swift
작업한 브랜치
- feature/ #23 
- Color 수정안 반영
- Typo 수정안 반영
-
- resolved : #23
=> [Fix] #23 - Color, Typo 수정안 반영

MC3-BeyondThe3F/MC3-BeyondThe3F/View/Components/MusicListRowView.swift, MC3-BeyondThe3F/MC3-BeyondThe3F/View/Components/MusicPlayerComponentView.swift, MC3-BeyondThe3F/MC3-BeyondThe3F/View/Components/ScopeButtonComponentView.swift, MC3-BeyondThe3F/MC3-BeyondThe3F/View/MapView.swift
작업한 브랜치
- feature/ #26 
- MapView playUI 구현
- 위치 보여주고 기능 구현하기
-
- resolved : #26
=> Feature/#26 - MapView playUI와 위치 보여주기

MC3-BeyondThe3F/MC3-BeyondThe3F/View/EditMapPositionView.swift, MC3-BeyondThe3F/MC3-BeyondThe3F/View/MapView.swift
작업한 브랜치
- feature/ #51 
- LocationHelper 제거
-
- resolved : #51
=> [Hotfix] #51 - LocationHelper 제거

MC3-BeyondThe3F/MC3-BeyondThe3F/View/Components/MusicSearchComponentView.swift
작업한 브랜치
- feature/ #55 
- MusicSearchView 프리뷰 부분 코드 수정 (MusicSearchView -> MusicSearchComponentView 로 수정)
-
- resolved : #55
=> [Fix] #55 - MusicSearchView 프리뷰 부분 코드 수정

MC3-BeyondThe3F/MC3-BeyondThe3F.xcodeproj/project.pbxproj, MC3-BeyondThe3F/MC3-BeyondThe3F/Model/MainVO.swift, MC3-BeyondThe3F/MC3-BeyondThe3F/View/MainTabView.swift
작업한 브랜치
- feature/ #61
- 뮤직킷 권한 받기 추가
-
=> 뮤직킷 권한 받기 추가

MC3-BeyondThe3F/MC3-BeyondThe3F/Model/MainDataModel.swift, MC3-BeyondThe3F/MC3-BeyondThe3F/Model/MusicDataModel.swift, MC3-BeyondThe3F/MC3-BeyondThe3F/Model/MusicItemVO.swift, MC3-BeyondThe3F/MC3-BeyondThe3F/Store/MC3_BeyondThe3F.xcdatamodeld/MC3_BeyondThe3F.xcdatamodel/contents, MC3-BeyondThe3F/MC3-BeyondThe3F/View/MainTabView.swift
작업한 브랜치
- feature/ #65
- MainDataModel.shared.getData 를 통해 가져오는 배열의 갯수를 최대 5개로 수정.
- songName과 artistName도 받아올 수 있도록 수정.
-
=> MainDataModel 수정

MC3-BeyondThe3F/MC3-BeyondThe3F.xcodeproj/project.pbxproj, MC3-BeyondThe3F/MC3-BeyondThe3F/Model/SearchDataModel.swift, MC3-BeyondThe3F/SearchDataModel.swift
작업한 브랜치
- feature/ #67
- SearchDataModel 추가
-
=> SearchDataModel 추가

MC3-BeyondThe3F/MC3-BeyondThe3F.xcodeproj/project.pbxproj, MC3-BeyondThe3F/MC3-BeyondThe3F/View/Components/MusicSearchComponentView.swift, MC3-BeyondThe3F/MC3-BeyondThe3F/View/MusicSearchView.swift
작업한 브랜치
- feature/ #33 
- 최근 검색 목록 뷰 구현
- 검색 결과 뷰 구현
- MusicSearchComponentView에서 @Binding var textInput: String로 수정 후 확인 가능
- musicSearchResultsListLow부분 MusicListRowView 컴포넌트 사용하고 싶은데 어떻게 써야할지 모르겠습니다. 저 또한 조금 더 고민해보겠지만, 이부분 확인해주시고 피드백해주시면 감사하겠습니다.
- resolved : #33
=> [Feat] #33 - MusicSearchView 음악 검색 뷰 및 기능 구현

MC3-BeyondThe3F/MC3-BeyondThe3F.xcodeproj/project.pbxproj, MC3-BeyondThe3F/MC3-BeyondThe3F/Global/Helper/AuthManger.swift
작업한 브랜치
- feature/ #71
- AuthManger를 추가함.
-
- resolved : #71
=> AuthManager 추가

MC3-BeyondThe3F/MC3-BeyondThe3F.xcodeproj/project.pbxproj
작업한 브랜치
- feature/ #73
- authManger 다시 추가
-
=> authManger 다시 추가

MC3-BeyondThe3F/MC3-BeyondThe3F.xcodeproj/project.pbxproj, MC3-BeyondThe3F/MC3-BeyondThe3F/Model/HistoryDataModel.swift, MC3-BeyondThe3F/MC3-BeyondThe3F/Model/dummy.swift, MC3-BeyondThe3F/MC3-BeyondThe3F/Store/MC3_BeyondThe3F.xcdatamodeld/MC3_BeyondThe3F.xcdatamodel/contents, MC3-BeyondThe3F/MC3-BeyondThe3F/View/MainTabView.swift, MC3-BeyondThe3F/MC3-BeyondThe3F/View/MusicSearchView.swift
작업한 브랜치
- feature/ #75
-
- resolved : #75
=> HistoryDataModel 추가

MC3-BeyondThe3F/MC3-BeyondThe3F.xcodeproj/project.pbxproj, MC3-BeyondThe3F/MC3-BeyondThe3F/Model/MusicPlayer.swift, MC3-BeyondThe3F/MC3-BeyondThe3F/View/MusicPlayView.swift
작업한 브랜치
- feature/ #85
- 
-
- resolved : #85
=> MusicPlayer 추가

MC3-BeyondThe3F/MC3-BeyondThe3F/View/Components/SFImageComponentView.swift, MC3-BeyondThe3F/MC3-BeyondThe3F/View/MusicPlayView.swift
작업한 브랜치
- feature/ #88 
- SFImageComponentView 파일에 backward 아이콘 추가
-
- resolved : #88
=> [Add] #88 - SFImageComponentView 파일에 backward 아이콘 추가

MC3-BeyondThe3F/MC3-BeyondThe3F/Model/MusicPlayer.swift, MC3-BeyondThe3F/MC3-BeyondThe3F/View/MainTabView.swift
작업한 브랜치
- feature/ #95 
- 
-
- resolved : #95
=> playlist 프라퍼티 옵저버 수정

MC3-BeyondThe3F/MC3-BeyondThe3F/Model/MusicPlayer.swift, MC3-BeyondThe3F/MC3-BeyondThe3F/View/MusicPlayView.swift
작업한 브랜치
- feature/ #90 
- MusicPlayView 음악 재생 뷰 및 기능 구현
- 데이터 모델 연결 (재생/일시정지, 앞 으로 스킵, 뒤로 스킵 기능)
-
- resolved : #90
=> [Feat] #90 - 데이터 모델 연결 (재생/일시정지, 앞 으로 스킵, 뒤로 스킵 기능)

MC3-BeyondThe3F/MC3-BeyondThe3F.xcodeproj/project.pbxproj, MC3-BeyondThe3F/MC3-BeyondThe3F/View/BucketView.swift, MC3-BeyondThe3F/MC3-BeyondThe3F/View/Components/MusicSearchComponentView.swift, MC3-BeyondThe3F/MC3-BeyondThe3F/View/EditDateView.swift, MC3-BeyondThe3F/MC3-BeyondThe3F/View/EditMapPositionView.swift, MC3-BeyondThe3F/MC3-BeyondThe3F/View/MapView.swift, MC3-BeyondThe3F/MC3-BeyondThe3F/View/MusicSearchView.swift
작업한 브랜치
- feature/ #99 
- 전체 프로세스 navigation 연결
-
- resolved : #99
=> [Feat] SearchView 연결

MC3-BeyondThe3F/MC3-BeyondThe3F/View/CarouselView.swift
작업한 브랜치
- feature/ #104 
- Musiclist List를 사용하여 구현하였습니다.
-
- resolved : #104
=> [Fix] #104 - Muisclist List 구현

MC3-BeyondThe3F/MC3-BeyondThe3F.xcodeproj/project.pbxproj, MC3-BeyondThe3F/MC3-BeyondThe3F/Model/MusicItemDataModel.swift, MC3-BeyondThe3F/MC3-BeyondThe3F/View/MainTabView.swift
작업한 브랜치
- feature/ #107 
-  musicId로 음악데이터가져오기
- 
- resolved : #107
=> musicId로 음악데이터가져오기

MC3-BeyondThe3F/MC3-BeyondThe3F/View/Components/MusicSearchComponentView.swift
작업한 브랜치
- feature/ #106 
- SearchComponentView 디자인 수정
- resolved : #106
=> [Design] #106 - SearchComponentView 디자인 수정

MC3-BeyondThe3F/MC3-BeyondThe3F/Model/MusicItemDataModel.swift, MC3-BeyondThe3F/MC3-BeyondThe3F/Model/dummy.swift, MC3-BeyondThe3F/MC3-BeyondThe3F/View/MainTabView.swift
작업한 브랜치
- feature/ #120 
- 
-
- resolved : #120
=> saveImage할 시, 코어데이터에 image 추가

MC3-BeyondThe3F/MC3-BeyondThe3F/View/ShazamView.swift
작업한 브랜치
- feature/ #115 
-  ShazamView 다시듣기 시 애니메이션이 다시 재생되지 않는 문제가 생겼는데 애니메이션 재생 시 기본값을 제공해줌으로 다시 재생시에도 애니메이션이 재생될 수 있게 수정
-
- resolved : #115
=> [Fix] ShazamView 다시듣기 시 애니메이션 재생 문제 해결

MC3-BeyondThe3F/MC3-BeyondThe3F.xcodeproj/project.pbxproj, MC3-BeyondThe3F/MC3-BeyondThe3F/Model/MusicPlayer.swift, MC3-BeyondThe3F/MC3-BeyondThe3F/Model/dummy.swift, MC3-BeyondThe3F/MC3-BeyondThe3F/View/Annotations/ClusteringAnnotationView.swift, MC3-BeyondThe3F/MC3-BeyondThe3F/View/Annotations/MusicAnnotationView.swift, MC3-BeyondThe3F/MC3-BeyondThe3F/View/MapMusicInfoView.swift, MC3-BeyondThe3F/MC3-BeyondThe3F/View/MapView.swift
작업한 브랜치
- feature/ #119 
- 코어데이터 연결
- 재생 기능 구현
- 검색 에러 해결
- MusicListItem 에서 편집 부분 클릭 시 ActionSheet
- 이후 아이템 편집, 삭제 기능이 CoreData에서 구현시 리스트 삭제, 편집 기능 추가 구현 예정
=> [Feat] MapView 기능 추가 구현

MC3-BeyondThe3F/MC3-BeyondThe3F/Model/MusicPlayer.swift, MC3-BeyondThe3F/MC3-BeyondThe3F/View/Components/MusicPlayerComponentView.swift
작업한 브랜치
- feature/ #127 
- Play 버튼 탭하면 일시정지 버튼으로 토글 > ObservedObject로 MusicPlayerComponentView와 MusicPlayView만 연결
-
- resolved : #127
=> [Feat] #127 - MusicPlayerComponentView

MC3-BeyondThe3F/MC3-BeyondThe3F/View/Components/MusicPlayerComponentView.swift, MC3-BeyondThe3F/MC3-BeyondThe3F/View/MusicPlayView.swift
작업한 브랜치
- feature/ #143 
- MusicPlayView와 MusicPlayerComponentView 디테일 작업
- 
- resolved : #143
=> [Feat] #143 - MusicPlayView와 MusicPlayerComponentView 디테일 작업 (3차)

MC3-BeyondThe3F/MC3-BeyondThe3F/Model/MusicPlayer.swift, MC3-BeyondThe3F/MC3-BeyondThe3F/View/MainTabView.swift, MC3-BeyondThe3F/MC3-BeyondThe3F/View/MusicPlayView.swift
작업한 브랜치
- feature/ #147 
- 
-  MusicPlayer클래스에 insertMusicAndPlay 매스드를 추가하는 방법으로, 노래 한개 넣기 기능을 추가함. 
-
- resolved : #147
=> 노래 한개 넣기 기능 추가

MC3-BeyondThe3F/MC3-BeyondThe3F.xcodeproj/project.pbxproj, MC3-BeyondThe3F/MC3-BeyondThe3F/Model/MusicItemDataModel.swift, MC3-BeyondThe3F/MC3-BeyondThe3F/View/MainTabView.swift
작업한 브랜치
- feature/ #151
- 
-
- resolved : #151
=> musicItem 추가 및 편집 기능 추가

MC3-BeyondThe3F/MC3-BeyondThe3F.xcodeproj/xcshareddata/xcschemes/MC3-BeyondThe3F.xcscheme, MC3-BeyondThe3F/MC3-BeyondThe3F/ContentView.swift, MC3-BeyondThe3F/MC3-BeyondThe3F/Global/Extension/ViewExtension.swift, MC3-BeyondThe3F/MC3-BeyondThe3F/Model/MusicAnnotation.swift, MC3-BeyondThe3F/MC3-BeyondThe3F/View/AddMusicView.swift, MC3-BeyondThe3F/MC3-BeyondThe3F/View/Annotations/ClusteringAnnotationView.swift, MC3-BeyondThe3F/MC3-BeyondThe3F/View/Annotations/MusicAnnotationView.swift, MC3-BeyondThe3F/MC3-BeyondThe3F/View/CarouselView.swift, MC3-BeyondThe3F/MC3-BeyondThe3F/View/Components/MapSearchComponentView.swift, MC3-BeyondThe3F/MC3-BeyondThe3F/View/Components/MusicListRowView.swift, MC3-BeyondThe3F/MC3-BeyondThe3F/View/EditDateView.swift, MC3-BeyondThe3F/MC3-BeyondThe3F/View/EditMapPositionView.swift, MC3-BeyondThe3F/MC3-BeyondThe3F/View/MainTabView.swift, MC3-BeyondThe3F/MC3-BeyondThe3F/View/MapMusicInfoView.swift, MC3-BeyondThe3F/MC3-BeyondThe3F/View/MapView.swift, MC3-BeyondThe3F/MC3-BeyondThe3F/View/MusicSearchView.swift, MC3-BeyondThe3F/MC3-BeyondThe3F/View/WorkThrough/WTMusicSearchView.swift
작업한 브랜치
- feature/ #142 
- MapView 디테일 에러 해결
- SearchView 디테일 에러 해결
- EditMapPositionView가 AddMusic 이후에 나타나는 에러 해결
-
- resolved : #142
=> [Fix] 전체 플로우 에러 핸들링

MC3-BeyondThe3F/MC3-BeyondThe3F/Model/MusicPlayer.swift, MC3-BeyondThe3F/MC3-BeyondThe3F/View/MusicPlayView.swift
작업한 브랜치
- feature/ #149 
- MusicPlayView에서 이미지 회전 수정
-
- resolved : #149
=> [Fix] #149 - MusicPlayView에서 이미지 회전 수정

MC3-BeyondThe3F/MC3-BeyondThe3F/Model/MusicPlayer.swift
작업한 브랜치
- feature/ #164
- insertMusicAndPlay 의 파라미터로 musicItem을 받도록 수정
-
- resolved : #164
=> insertMusicAndPlay 의 파라미터로 musicItem을 받도록 수정

MC3-BeyondThe3F/MC3-BeyondThe3F.xcodeproj/project.pbxproj, MC3-BeyondThe3F/MC3-BeyondThe3F/Model/MusicItemDataModel.swift, MC3-BeyondThe3F/MC3-BeyondThe3F/Model/MusicPlayer.swift, MC3-BeyondThe3F/MC3-BeyondThe3F/View/AddMusicView.swift, MC3-BeyondThe3F/MC3-BeyondThe3F/View/CarouselView.swift, MC3-BeyondThe3F/MC3-BeyondThe3F/View/Components/MusicPlayerComponentView.swift, MC3-BeyondThe3F/MC3-BeyondThe3F/View/EditDateView.swift, MC3-BeyondThe3F/MC3-BeyondThe3F/View/MainTabView.swift, MC3-BeyondThe3F/MC3-BeyondThe3F/View/MapMusicInfoView.swift, MC3-BeyondThe3F/MC3-BeyondThe3F/View/MusicPlayView.swift
작업한 브랜치
- feature/ #160
- MusicPlayComponentView 에러 수정
-
=> [Fix] MusicPlay 구현

MC3-BeyondThe3F/MC3-BeyondThe3F.xcodeproj/project.pbxproj, MC3-BeyondThe3F/MC3-BeyondThe3F/View/AddMusicView.swift, MC3-BeyondThe3F/MC3-BeyondThe3F/View/BucketView.swift, MC3-BeyondThe3F/MC3-BeyondThe3F/View/Components/ToastComponentView.swift, MC3-BeyondThe3F/MC3-BeyondThe3F/View/MapMusicInfoView.swift, MC3-BeyondThe3F/MC3-BeyondThe3F/View/MapView.swift, MC3-BeyondThe3F/MC3-BeyondThe3F/ViewModel/MusicItemUpdateViewModel.swift
작업한 브랜치
- feature/ #166 
- ToastComponentView 구현
-
- resolved : #166
=> [Feat] #166 - ToastComponentView 구현

MC3-BeyondThe3F/MC3-BeyondThe3F.xcodeproj/project.pbxproj, MC3-BeyondThe3F/MC3-BeyondThe3F/Model/MusicItemExtension.swift, MC3-BeyondThe3F/MC3-BeyondThe3F/Model/MusicPlayer.swift, MC3-BeyondThe3F/MC3-BeyondThe3F/View/CarouselView.swift, MC3-BeyondThe3F/MC3-BeyondThe3F/View/Components/MusicPlayerComponentView.swift, MC3-BeyondThe3F/MC3-BeyondThe3F/View/MainTabView.swift, MC3-BeyondThe3F/MC3-BeyondThe3F/View/MapMusicInfoView.swift, MC3-BeyondThe3F/MC3-BeyondThe3F/View/MusicSearchView.swift, MC3-BeyondThe3F/MC3-BeyondThe3F/View/WorkThrough/WTMusicSearchView.swift
작업한 브랜치
- feature/ #168 
- 
-
- resolved : #168
=> musicItemVO로 변경.

MC3-BeyondThe3F/MC3-BeyondThe3F.xcodeproj/project.pbxproj, MC3-BeyondThe3F/MC3-BeyondThe3F/ContentView.swift, MC3-BeyondThe3F/MC3-BeyondThe3F/Model/MusicItemDataModel.swift, MC3-BeyondThe3F/MC3-BeyondThe3F/Model/MusicPlayer.swift, MC3-BeyondThe3F/MC3-BeyondThe3F/View/AddMusicView.swift, MC3-BeyondThe3F/MC3-BeyondThe3F/View/EditDateView.swift, MC3-BeyondThe3F/MC3-BeyondThe3F/View/EditMapPositionView.swift, MC3-BeyondThe3F/MC3-BeyondThe3F/View/MainTabView.swift, MC3-BeyondThe3F/MC3-BeyondThe3F/View/MapMusicInfoView.swift, MC3-BeyondThe3F/MC3-BeyondThe3F/View/MusicPlayView.swift, MC3-BeyondThe3F/MC3-BeyondThe3F/View/MusicSearchView.swift
작업한 브랜치
- feature/ #160 
- MusicPlayer 에러 해결
- MapView에러 해결
- 워크쓰루 에러 해결
-
- resolved : #160
=> [Fix] 전체 플로우 에러 수정

MC3-BeyondThe3F/MC3-BeyondThe3F.xcodeproj/project.pbxproj, MC3-BeyondThe3F/MC3-BeyondThe3F/Model/MusicPlayer.swift
작업한 브랜치
- feature/ #177
-  노래를 중간에 끼워 넣지 않고, 맨 앞에 넣는 방법으로 음악이 플레이 되지 않는 오류 해결
-
- resolved : #177
=> 노래를 중간에 끼워 넣지 않고, 맨 앞에 넣는 방법으로 음악이 플레이 되지 않는 오류 해결

MC3-BeyondThe3F/MC3-BeyondThe3F.xcodeproj/project.pbxproj, MC3-BeyondThe3F/MC3-BeyondThe3F/Model/MusicPlayer.swift, MC3-BeyondThe3F/MC3-BeyondThe3F/View/AddMusicView.swift, MC3-BeyondThe3F/MC3-BeyondThe3F/View/BucketView.swift, MC3-BeyondThe3F/MC3-BeyondThe3F/View/CarouselView.swift, MC3-BeyondThe3F/MC3-BeyondThe3F/View/Components/MusicListRowView.swift, MC3-BeyondThe3F/MC3-BeyondThe3F/View/Components/MusicPlayerComponentView.swift, MC3-BeyondThe3F/MC3-BeyondThe3F/View/Components/ToastComponentView.swift, MC3-BeyondThe3F/MC3-BeyondThe3F/View/EditMapPositionView.swift, MC3-BeyondThe3F/MC3-BeyondThe3F/View/MainTabView.swift, MC3-BeyondThe3F/MC3-BeyondThe3F/View/MapMusicInfoView.swift, MC3-BeyondThe3F/MC3-BeyondThe3F/View/MapView.swift, MC3-BeyondThe3F/MC3-BeyondThe3F/View/MusicPlayView.swift, MC3-BeyondThe3F/MC3-BeyondThe3F/View/MusicSearchView.swift, MC3-BeyondThe3F/MC3-BeyondThe3F/View/WorkThrough/WTMusicSearchView.swift, MC3-BeyondThe3F/MC3-BeyondThe3F/ViewModel/MusicItemUpdateViewModel.swift
작업한 브랜치
- feature/ #175 
-
- resolved : #175
=> [Fix] #175 - 디자인 디테일 수정

MC3-BeyondThe3F/MC3-BeyondThe3F.xcodeproj/project.pbxproj, MC3-BeyondThe3F/MC3-BeyondThe3F.xcodeproj/xcshareddata/xcschemes/MC3-BeyondThe3F.xcscheme, MC3-BeyondThe3F/MC3-BeyondThe3F/Global/Extension/DateExtension.swift, MC3-BeyondThe3F/MC3-BeyondThe3F/Global/Helper/Double.swift, MC3-BeyondThe3F/MC3-BeyondThe3F/Model/MusicItemDataModel.swift, MC3-BeyondThe3F/MC3-BeyondThe3F/Model/dummy.swift, MC3-BeyondThe3F/MC3-BeyondThe3F/View/MusicPlayView.swift
작업한 브랜치
- feature/ #183 
- playlist delete index 에러 수정
-
- resolved : #183
=> [Fix] #183 - playlist delete index 에러 수정

MC3-BeyondThe3F/MC3-BeyondThe3F/Source/Components/MusicPlayerComponentView.swift, MC3-BeyondThe3F/MC3-BeyondThe3F/Source/Model/MusicPlayer.swift, MC3-BeyondThe3F/MC3-BeyondThe3F/Source/View/EditView/EditMapPositionView.swift, MC3-BeyondThe3F/MC3-BeyondThe3F/Source/View/EditView/EditMapUIView.swift, MC3-BeyondThe3F/MC3-BeyondThe3F/Source/View/PlayView/MusicPlayView.swift
작업한 브랜치
- feature/ #188 
- MusicPlayer index 삭제가 이전 인덱스가 되는 에러 해결
- MapView에서 임의 재생시 앱이 종료되는 에러 해결
- + EditMapPostionView에서 현재 위치 정보를 받아오지 못하는 에러 해결
-
- resolved : #188
=> [Fix] Player 에러 수정

MC3-BeyondThe3F/MC3-BeyondThe3F.xcodeproj/project.pbxproj, MC3-BeyondThe3F/MC3-BeyondThe3F/Source/Components/MusicPlayerComponentView.swift, MC3-BeyondThe3F/MC3-BeyondThe3F/Source/Utils/Manager/MusicSubscriptionManager.swift, MC3-BeyondThe3F/MC3-BeyondThe3F/Source/View/PlayView/MusicPlayView.swift
작업한 브랜치
- feature/ #190
- MusicPlayComponentView에 SubscriptionOffer 구현
- MusicPlayView에 SubscriptionOffer 구현
- 기존에 애플뮤직이 없는 유저 대상으로 테스트 필요
- resolved : #190
=> [Feat] SubscriptionOffer 기능 구현

MC3-BeyondThe3F/MC3-BeyondThe3F/Source/View/MapView/MapMusicInfoView.swift
지도뷰 Modal 에러 수정
작업한 브랜치
- feature/ #195 
- 지도 뷰에서 Modal이 하단으로 내려가지 않는 에러를 수정하였습니다. 
|기능|스크린샷|
|:--:|:--:|
|MapView|<img src = "https://github.com/DeveloperAcademy-POSTECH/MC3-Team11-BeyondThe3F/assets/105622985/ff7d6036-5fbe-408d-b647-b965a010ea91" width ="250">|
- resolved : #195
=> [Fix] 지도뷰 Modal 에러 수정
